[release-branch.go1.25] crypto/x509: fix wildcard domain exclusions.
This fixes the case of an exclusion of bar.com being applied to a
certificate for *.foo.com. When only applying the test change, this
error shows the issue:

    --- FAIL: TestConstraintCases/#99 (0.00s)
        name_constraints_test.go:2198: unexpected failure: x509: a root or intermediate certificate is not authorized to sign for this name: DNS name "*.bar.example.com" is excluded by constraint "foo.example.com"

See change I60fba0d635f23d53f2146cb64b9f6a29755712e3 for a matching
change to master to just add the test cases (which are already passing
there and in Go 1.26).

Found as part of https://issues.chromium.org/issues/488306305.

Fixes #77968

Change-Id: I747e51edc16c1111f6a114de33af35f618793c90
Reviewed-on: https://go-review.googlesource.com/c/go/+/750980
Reviewed-by: Roland Shoemaker <roland@golang.org>
LUCI-TryBot-Result: Go LUCI <golang-scoped@luci-project-accounts.iam.gserviceaccount.com>